### ISSUE TITLE
Not implemented on Production but do sees it local 

### ISSUE THREAD

**Issue by instasck** [ivelum/djangoql#68] opened 2021-03-22 23:40 UTC
If I run the same code on local pc - http://127.0.0.1:8000 - I will see the search working really cool.
While running as a service on linux production env - I don't see the feature working at all !
![image](https://user-images.githubusercontent.com/43851500/112071574-bab9b080-8b78-11eb-9815-e3afc81a31d6.png)

Should I remove any files ?

**Comment by stebunovd** [comment] 2021-03-23 05:58
hi @instasck, I guess that the issue is probably not related to DjangoQL itself. I'd recommend double-checking that you're running the same code in production as in your local environment and that the relevant configuration is the same.

**Comment by instasck** [comment] 2021-03-23 08:38
It is for sure the same code.
I checked the debug.log and saw no errors.
Any idea ? I am not a professional django dev.

**Comment by stebunovd** [comment] 2021-03-23 09:33
it can be various things - for example, make sure that you have restarted the services so that the code on the disk is the same that is actually running in memory. Or, maybe it's something with the configuration; maybe the code receives different parameters in production and behaves differently because of that. 

anyway, currently, I don't see any signs that it could be a problem with DjangoQL itself, so closing this issue for now. If you think it's actually a bug in DjangoQL, please provide steps to reproduce, and I'll be happy to reopen it and investigate.

**Closed by stebunovd** 2021-03-23 09:33 UTC

**Comment by instasck** [comment] 2021-04-06 09:54
python manage.py collectstatic
recreate static file
